# Generated by Django 2.1.7 on 2019-08-02 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20190802_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='douyin_info',
            name='d_updata_time',
            field=models.DateTimeField(null=True),
        ),
    ]
